CREATE TABLE IF NOT EXISTS people
(
    personid int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar(50) NOT NULL,
    year_of_birth int NOT NULL
);

CREATE TABLE IF NOT EXISTS books
(
    bookid int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personid int REFERENCES people (personid) ON DELETE SET NULL,
    title varchar(50) NOT NULL,
    author varchar(50) NOT NULL,
    year int
);